# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cap_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=16, verbose_name='teamname')),
                ('cname', models.CharField(max_length=16, verbose_name='cname')),
                ('cstunum', models.IntegerField(verbose_name='cstunum')),
                ('cschool', models.CharField(max_length=16, verbose_name='cschool')),
                ('clianix', models.CharField(max_length=32, verbose_name='clianxi')),
                ('othermember', models.CharField(blank=True, max_length=128, verbose_name='othermember')),
                ('otherstunum', models.CharField(blank=True, max_length=128, verbose_name='otherstunum')),
                ('otherschool', models.CharField(blank=True, max_length=64, verbose_name='otherschool')),
            ],
        ),
    ]
