# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('othermember', models.CharField(blank=True, max_length=128, verbose_name='othermember')),
                ('otherstunum', models.CharField(blank=True, max_length=128, verbose_name='otherstunum')),
                ('otherschool', models.CharField(blank=True, max_length=64, verbose_name='otherschool')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=16, verbose_name='teamname')),
                ('cname', models.CharField(max_length=16, verbose_name='cname')),
                ('cstunum', models.IntegerField(verbose_name='cstunum')),
                ('cschool', models.CharField(max_length=16, verbose_name='cschool')),
                ('clianix', models.CharField(max_length=32, verbose_name='clianxi')),
            ],
        ),
        migrations.DeleteModel(
            name='Cap_Info',
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.TeamInfo'),
        ),
    ]
