# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171021_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaminfo',
            old_name='clianix',
            new_name='clianxi',
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='cstunum',
            field=models.CharField(max_length=16, verbose_name='cstunum'),
        ),
    ]
