# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171021_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
