# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_member_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='teamnum',
            field=models.IntegerField(default=0),
        ),
    ]
