# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_teaminfo_teamnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='cstunum',
            field=models.CharField(max_length=16, unique=True, verbose_name='cstunum'),
        ),
    ]
