# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20171021_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='teamtype',
            field=models.CharField(default=0, max_length=2, verbose_name='teamname'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='teamname',
            field=models.CharField(max_length=16, unique=True, verbose_name='teamname'),
        ),
    ]
