# Generated by Django 2.1.3 on 2018-11-07 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20171023_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=django.utils.timezone.now, upload_to='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('teamName', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
