# Generated by Django 2.1.3 on 2018-11-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='fileName',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
